spring:
  application:
    name: spring-boot-ScvQ
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///boot?characterEncoding=utf8&useSSL=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
  jackson:  #jackson
    serialization:
         indent-output: false
  http: #开启上传文件
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100Mb
      max-request-size: 100Mb
      location: #
server:
  port: 8080
banner:
  location: banner/banner.txt